services:
  ubuntu-console:
    image: ubuntu:noble
    hostname: ubuntu.hcloud.com
    command: ["/usr/bin/tail", "-f", "/dev/null"]
    deploy:
      replicas: 1

  debian-console:
    build: ./images/debian
    hostname: debian.hcloud.com
    command: ["/usr/bin/tail", "-f", "/dev/null"]
    deploy:
      replicas: 1

  nginx:
    image: nginx
    hostname: nginx.hcloud.com
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf.d-default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/nginx/log:/var/log/nginx
      - ./volumes/nginx/site:/usr/share/nginx/html
    deploy:
      replicas: 1

  redis:
    image: redis
    hostname: redis.hcloud.com
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./volumes/redis/data:/data
      - ./volumes/redis/logs:/logs
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      replicas: 1

  #  h-mariadb:
  #    image: mariadb:10
  #    hostname: mariadb.hcloud.com
  #    ports:
  #      - "3306:3306"
  #    env_file:
  #      - ./mariadb.env
  #    volumes:
  #      - ./volumes/mariadb:/var/lib/mysql
  #    deploy:
  #      replicas: 1

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ry
      MYSQL_USER: ruoyi
      MYSQL_PASSWORD: ruoyi123456
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq.hcloud.com
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
      - ./erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    deploy:
      replicas: 1

  emqx:
    image: emqx/emqx:4.3.5
    hostname: emqx.hcloud.com
    ports:
      - "31883:1883"
      - "31083:18083"
    env_file:
      - ./emqx.env
    volumes:
      - ./volumes/emqx/data:/opt/emqx/data
      - ./volumes/emqx/etc:/opt/emqx/etc
      - ./volumes/emqx/log:/opt/emqx/log
    deploy:
      replicas: 1

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto.hcloud.com
    ports:
      - "21883:1883"
      - "29001:9001"
    env_file:
      - ./mosquitto.env
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./volumes/mosquitto/data:/mosquitto/data
      #- ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/log:/mosquitto/log
    deploy:
      replicas: 1

  emqx-c1:
    image: emqx/emqx:4.3.5
    hostname: emqx-c1.hcloud.com
    #ports:
    #  - "31981:1883"
    #  - "31981:18083"
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=emqx-c1.hcloud.com"
      - "EMQX_CLUSTER__DISCOVERY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@emqx-c1.hcloud.com, emqx@emqx-c2.hcloud.com"
    volumes:
      - ./volumes/emqx-c1/data:/opt/emqx/data
      - ./volumes/emqx-c1/etc:/opt/emqx/etc
      - ./volumes/emqx-c1/log:/opt/emqx/log

  emqx-c2:
    image: emqx/emqx:4.3.5
    hostname: emqx-c2.hcloud.com
    #ports:
    #  - "31982:1883"
    #  - "31982:18083"
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=emqx-c2.hcloud.com"
      - "EMQX_CLUSTER__DISCOVERY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx-c1.hcloud.com, emqx@emqx-c2.hcloud.com"
    volumes:
      - ./volumes/emqx-c2/data:/opt/emqx/data
      - ./volumes/emqx-c2/etc:/opt/emqx/etc
      - ./volumes/emqx-c2/log:/opt/emqx/log

  zookeeper-1:
    image: zookeeper:3.6
    hostname: zk1.hcloud.com
    restart: always
    ports:
      - 2181:2181
    volumes:
      - ./volumes/zookeeper/1/data:/data
      - ./volumes/zookeeper/1/datalog:/datalog
      - ./volumes/zookeeper/1/logs:/logs
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2.hcloud.com:2888:3888;2181 server.3=zk3.hcloud.com:2888:3888;2181

  zookeeper-2:
    image: zookeeper:3.6
    hostname: zk2.hcloud.com
    restart: always
    ports:
      - 2182:2181
    volumes:
      - ./volumes/zookeeper/2/data:/data
      - ./volumes/zookeeper/2/datalog:/datalog
      - ./volumes/zookeeper/2/logs:/logs
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1.hcloud.com:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3.hcloud.com:2888:3888;2181

  zookeeper-3:
    image: zookeeper:3.6
    hostname: zk3.hcloud.com
    restart: always
    ports:
      - 2183:2181
    volumes:
      - ./volumes/zookeeper/3/data:/data
      - ./volumes/zookeeper/3/datalog:/datalog
      - ./volumes/zookeeper/3/logs:/logs
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1.hcloud.com:2888:3888;2181 server.2=zk2.hcloud.com:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  kafka-zookeeper:
    image: docker.io/bitnami/zookeeper:3-debian-10
    hostname: kafka-zk.hcloud.com
    ports:
      - 12181:2181
    volumes:
      - ./volumes/kafka/zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2-debian-10
    hostname: kafka.hcloud.com
    ports:
      - 9092:9092
    volumes:
      - ./volumes/kafka/kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka-zk.hcloud.com:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - h-kafka-zookeeper

  mongo:
    image: mongo:4.4.6-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo/data/db:/data/db
    env_file:
      - ./mongo.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 28081:8081
    env_file:
      - ./mongo-express.env
#volumes:
#  db-data:

#networks:
#  overlay:
