version: "3.9"

services:

  h-ubuntu-console:
    image: ubuntu:focal
    hostname: ubuntu.hcloud.com
    command: ["/usr/bin/tail", "-f", "/dev/null"]
    deploy:
      replicas: 1

  h-debian-console:
    build: ./images/debian
    hostname: debian.hcloud.com
    command: ["/usr/bin/tail", "-f", "/dev/null"]
    deploy:
      replicas: 1

  h-nginx:
    image: nginx:1.19.6
    hostname: nginx.hcloud.com
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf.d-default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/nginx/log:/var/log/nginx
      - ./volumes/nginx/site:/usr/share/nginx/html
    deploy:
      replicas: 1

  h-redis:
    image: redis:6
    hostname: redis.hcloud.com
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data:/data
      - ./volumes/redis/logs:/logs
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      replicas: 1

  h-mariadb:
    image: mariadb:10
    hostname: mariadb.hcloud.com
    ports:
      - "3306:3306"
    env_file:
      - ./mariadb.env
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    deploy:
      replicas: 1

  h-rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq.hcloud.com
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
      - ./erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    deploy:
      replicas: 1

  h-zookeeper-1:
    image: zookeeper:3.6
    hostname: zk1.hcloud.com
    restart: always
    ports:
      - 2181:2181
    volumes:
      - ./volumes/zookeeper/1/data:/data
      - ./volumes/zookeeper/1/datalog:/datalog
      - ./volumes/zookeeper/1/logs:/logs
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2.hcloud.com:2888:3888;2181 server.3=zk3.hcloud.com:2888:3888;2181

  h-zookeeper-2:
    image: zookeeper:3.6
    hostname: zk2.hcloud.com
    restart: always
    ports:
      - 2182:2181
    volumes:
      - ./volumes/zookeeper/2/data:/data
      - ./volumes/zookeeper/2/datalog:/datalog
      - ./volumes/zookeeper/2/logs:/logs
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1.hcloud.com:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=h-zk3.hcloud.com:2888:3888;2181

  h-zookeeper-3:
    image: zookeeper:3.6
    hostname: zk3.hcloud.com
    restart: always
    ports:
      - 2183:2181
    volumes:
      - ./volumes/zookeeper/3/data:/data
      - ./volumes/zookeeper/3/datalog:/datalog
      - ./volumes/zookeeper/3/logs:/logs
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1.hcloud.com:2888:3888;2181 server.2=zk2.hcloud.com:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  h-kafka-zookeeper:
    image: docker.io/bitnami/zookeeper:3-debian-10
    hostname: kafka-zk.hcloud.com
    ports:
      - 12181:2181
    volumes:
      - ./volumes/kafka/zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  h-kafka:
    image: docker.io/bitnami/kafka:2-debian-10
    hostname: kafka.hcloud.com
    ports:
      - 9092:9092
    volumes:
      - ./volumes/kafka/kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka-zk.hcloud.com:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - h-kafka-zookeeper

#volumes:
#  db-data:

#networks:
#  overlay:

